# Generated by Django 4.2.4 on 2023-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingosapp', '0003_contactprofile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
