# Generated by Django 4.2.4 on 2023-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_desc', models.CharField(max_length=255)),
                ('fiber_in_g', models.DecimalField(decimal_places=2, max_digits=50)),
                ('kcal_in_100g', models.DecimalField(decimal_places=2, max_digits=50)),
                ('mg_in_mg', models.DecimalField(decimal_places=2, max_digits=50)),
                ('zn_in_mg', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fa_in_mcg', models.DecimalField(decimal_places=10, max_digits=50)),
                ('p_in_mg', models.DecimalField(decimal_places=2, max_digits=50)),
                ('vitamin_a_in_mcg', models.DecimalField(decimal_places=2, max_digits=50)),
                ('vitamin_c_in_mg', models.DecimalField(decimal_places=2, max_digits=50)),
                ('vitamin_e_in_mg', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'fruits_vegetables',
            },
        ),
        migrations.CreateModel(
            name='RefValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=250)),
                ('ref_value', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'refvalue',
            },
        ),
    ]
