# Generated by Django 4.2.5 on 2023-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='price',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber_in_g',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='kcal_in_100g',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='long_desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='mg_in_mg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='p_in_mg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamin_a_in_mcg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamin_c_in_mg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamin_e_in_mg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='zn_in_mg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='fooditem',
            table='fruits_vegetables',
        ),
    ]
