# Generated by Django 4.2.4 on 2023-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_fooditem_description_remove_fooditem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=250)),
                ('ref_value', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'refvalue',
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fa_in_mcg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fiber_in_g',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='kcal_in_100g',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='mg_in_mg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='p_in_mg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vitamin_a_in_mcg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vitamin_c_in_mg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vitamin_e_in_mg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='zn_in_mg',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
